# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_window4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerWindow(object):
    def setupUi(self, ServerWindow):
        ServerWindow.setObjectName("ServerWindow")
        ServerWindow.resize(548, 582)
        self.centralwidget = QtWidgets.QWidget(ServerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 80, 351, 31))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.CustomServer = QtWidgets.QLineEdit(self.centralwidget)
        self.CustomServer.setGeometry(QtCore.QRect(220, 240, 201, 31))
        self.CustomServer.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.CustomServer.setObjectName("CustomServer")
        self.ServerWindow_NextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ServerWindow_NextBtn.setGeometry(QtCore.QRect(180, 460, 151, 51))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(12)
        self.ServerWindow_NextBtn.setFont(font)
        self.ServerWindow_NextBtn.setObjectName("ServerWindow_NextBtn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.CustomKey = QtWidgets.QLineEdit(self.centralwidget)
        self.CustomKey.setGeometry(QtCore.QRect(220, 280, 201, 31))
        self.CustomKey.setObjectName("CustomKey")
        self.UseOfficialServer = QtWidgets.QCheckBox(self.centralwidget)
        self.UseOfficialServer.setGeometry(QtCore.QRect(170, 340, 171, 31))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(12)
        self.UseOfficialServer.setFont(font)
        self.UseOfficialServer.setObjectName("UseOfficialServer")
        ServerWindow.setCentralWidget(self.centralwidget)
        self.UseOfficialServer.stateChanged.connect(self.change_toggle)

        self.retranslateUi(ServerWindow)
        QtCore.QMetaObject.connectSlotsByName(ServerWindow)

    # 使用官方服务器打勾之后，使自定义服务器地址和Key输入框失效
    def change_toggle(self, state):
        if state == QtCore.Qt.Checked:
            self.CustomServer.setEnabled(False)
            self.CustomKey.setEnabled(False)
        else:
            self.CustomServer.setEnabled(True)
            self.CustomKey.setEnabled(True)

    def retranslateUi(self, ServerWindow):
        _translate = QtCore.QCoreApplication.translate
        ServerWindow.setWindowTitle(_translate("ServerWindow", "服务器设置"))
        self.label.setText(_translate("ServerWindow", "请按照技术人员的要求填写此页"))
        self.label_2.setText(_translate("ServerWindow", "服务器地址"))
        self.CustomServer.setPlaceholderText(_translate("ServerWindow", "留空以不做修改"))
        self.ServerWindow_NextBtn.setText(_translate("ServerWindow", "下一步"))
        self.label_3.setText(_translate("ServerWindow", "Key"))
        self.CustomKey.setPlaceholderText(_translate("ServerWindow", "留空以不做修改"))
        self.UseOfficialServer.setText(_translate("ServerWindow", "使用官方服务器"))
