# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_window5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReadyWindow(object):
    def setupUi(self, ReadyWindow):
        ReadyWindow.setObjectName("ReadyWindow")
        ReadyWindow.resize(548, 582)
        self.centralwidget = QtWidgets.QWidget(ReadyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ReadyWindow_NextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ReadyWindow_NextBtn.setGeometry(QtCore.QRect(180, 480, 151, 51))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(12)
        self.ReadyWindow_NextBtn.setFont(font)
        self.ReadyWindow_NextBtn.setObjectName("ReadyWindow_NextBtn")
        ReadyWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ReadyWindow)
        QtCore.QMetaObject.connectSlotsByName(ReadyWindow)

    def retranslateUi(self, ReadyWindow):
        _translate = QtCore.QCoreApplication.translate
        ReadyWindow.setWindowTitle(_translate("ReadyWindow", "就快好了"))
        self.ReadyWindow_NextBtn.setText(_translate("ReadyWindow", "下一步"))
