# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TermsWindow(object):
    def setupUi(self, TermsWindow):
        TermsWindow.setObjectName("TermsWindow")
        TermsWindow.resize(548, 582)
        self.centralwidget = QtWidgets.QWidget(TermsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(110, 150, 331, 291))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.TermsWindow_AllowBtn = QtWidgets.QCheckBox(self.centralwidget)
        self.TermsWindow_AllowBtn.setGeometry(QtCore.QRect(120, 460, 301, 31))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(15)
        self.TermsWindow_AllowBtn.setFont(font)
        self.TermsWindow_AllowBtn.setObjectName("TermsWindow_AllowBtn")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 50, 332, 97))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(20)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.TermsWindow_NextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TermsWindow_NextBtn.setGeometry(QtCore.QRect(190, 500, 151, 51))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(12)
        self.TermsWindow_NextBtn.setFont(font)
        self.TermsWindow_NextBtn.setObjectName("TermsWindow_NextBtn")
        self.TermsWindow_NextBtn.setEnabled(False)
        self.TermsWindow_AllowBtn.stateChanged.connect(lambda: self.TermsWindow_NextBtn.setEnabled(
            True) if self.TermsWindow_AllowBtn.isChecked() else self.TermsWindow_NextBtn.setEnabled(
            False))

        TermsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TermsWindow)
        QtCore.QMetaObject.connectSlotsByName(TermsWindow)

    def retranslateUi(self, TermsWindow):
        _translate = QtCore.QCoreApplication.translate
        TermsWindow.setWindowTitle(_translate("TermsWindow", "用户协议"))
        self.plainTextEdit.setPlainText(_translate("TermsWindow", "1\n"
"2\n"
"3\n"
"4\n"
"5\n"
"6\n"
"7\n"
"8\n"
"9\n"
"0\n"
"1\n"
"2\n"
"3\n"
"4\n"
"46\n"
"6\n"
"7\n"
"g\n"
"hgf"))
        self.TermsWindow_AllowBtn.setText(_translate("TermsWindow", "我已阅读并同意以上协议"))
        self.label.setText(_translate("TermsWindow", "在使用之前"))
        self.label_2.setText(_translate("TermsWindow", "请阅读我们的服务协议"))
        self.TermsWindow_NextBtn.setText(_translate("TermsWindow", "下一步"))
