# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TermsWindow(object):
    def setupUi(self, TermsWindow):
        TermsWindow.setObjectName("TermsWindow")
        TermsWindow.resize(548, 582)
        self.centralwidget = QtWidgets.QWidget(TermsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(110, 150, 331, 291))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.TermsWindow_AllowBtn = QtWidgets.QCheckBox(self.centralwidget)
        self.TermsWindow_AllowBtn.setGeometry(QtCore.QRect(120, 460, 301, 31))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(15)
        self.TermsWindow_AllowBtn.setFont(font)
        self.TermsWindow_AllowBtn.setObjectName("TermsWindow_AllowBtn")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 50, 332, 97))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(20)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.TermsWindow_NextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TermsWindow_NextBtn.setGeometry(QtCore.QRect(190, 500, 151, 51))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(12)
        self.TermsWindow_NextBtn.setFont(font)
        self.TermsWindow_NextBtn.setObjectName("TermsWindow_NextBtn")
        self.TermsWindow_NextBtn.setEnabled(False)
        self.TermsWindow_AllowBtn.stateChanged.connect(lambda: self.TermsWindow_NextBtn.setEnabled(
            True) if self.TermsWindow_AllowBtn.isChecked() else self.TermsWindow_NextBtn.setEnabled(
            False))

        TermsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TermsWindow)
        QtCore.QMetaObject.connectSlotsByName(TermsWindow)

    def retranslateUi(self, TermsWindow):
        _translate = QtCore.QCoreApplication.translate
        TermsWindow.setWindowTitle(_translate("TermsWindow", "用户协议"))
        self.plainTextEdit.setPlainText(_translate("TermsWindow",
"远程诊断维修服务用户协议 V1.0\n"
"版本更新日期：2024年10月29日\n"
"\n"
"欢迎使用“远程诊断维修服务”程序（以下简称“本软件”）。在您开始使用本软件前，请您仔细阅读并理解本协议的所有条款和条件。使用本软件，即表示您同意遵守本协议的所有条款。如果您不同意，请勿使用本软件。\n"
"\n"
"1. 本协议是您个人与东北大学先锋网络中心（以下简称“我们”）之间就本软件的下载、安装、使用和相关服务而订立的协议。在您同意本协议并遵守相应条款的前提下，我们授予您在Windows平台上安装和使用本软件的权限。\n"
"\n"
"2.本软件由“远程诊断维修服务自动诊断”（以下简称“启动器”）与“远程诊断维修服务人工诊断” （以下简称“远控程序”）两部分组成。其中远控程序为基于开源软件 RustDesk v1.4.2 二次开发而来的程序，启动器为先锋网络中心独立开发的程序。二者均已在Github平台上开源。\n"
"\n"
"3. 在使用本软件期间，为确保远程诊断维修服务正常进行，软件可能会自动获取您的网络状态、部分系统配置，以及获取您在东北大学一网通办中预留的个人信息。我们承诺仅在远程诊断维修服务进行时使用您的数据，且仅用于确保软件功能的正常运行与服务的正常继续，除非取得您的明确授权，或根据法律法规的要求，我们不会将您的数据分享给第三方。\n"
"\n"
"4. 您应理解并同意，如果您遇到的问题经我们远程诊断后不适用于远程维修的，我们有权终止本次远程维修。此时，您应携带您的电脑及其他必要配件，前往指定地点进行线下维修。\n"
"\n"
"5. 由于本软件为开源软件，用户可自行获取和查看源代码。我们不对任何第三方基于本软件代码的修改或重新发布行为负责，您应自行审查和判断第三方修改的安全性。本软件作为开源软件，可能存在漏洞或缺陷。在法律允许的范围内，我们不对因使用或无法使用本软件而导致的任何直接、间接、附带或间接损失承担责任。\n"
"\n"
"6. 本软件的知识产权（包括但不限于名称、商标、标识、内容等）归我们或相关权利人所有。在开源许可的范围内，您可以复制、修改和分发源代码，但不得违反开源许可证的规定。未经许可，您不得以任何形式擅自使用商标或标识。\n"
"\n"
"7. 本协议最终解释权归东北大学先锋网络中心所有。\n"
))
        self.TermsWindow_AllowBtn.setText(_translate("TermsWindow", "我已阅读并同意以上协议"))
        self.label.setText(_translate("TermsWindow", "在使用之前"))
        self.label_2.setText(_translate("TermsWindow", "请阅读我们的服务协议"))
        self.TermsWindow_NextBtn.setText(_translate("TermsWindow", "下一步"))
